### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by yebai** [TuringLang/DistributionsAD.jl#102]
There are some significant refactoring #95 and bug-fixing #97 merged recently. Are there any other stuff that we should address before a new release?

**Comment by devmotion** [comment]
Let's just fix the compat bounds, then it should be fine to make a new bugfix release. The git history is a bit messed up since we didn't squash before merging but AFAICT the changes were just separating the backends more clearly and fixing the issues with PDMats 0.10.

**Comment by nmheim** [comment]
Sorry for not squashing, that was my mistake. It only moved code though (unless I really messed up).

**Comment by devmotion** [comment]
No worries, it's great that you improved the organization and separation of the backends :+1:

**Comment by devmotion** [comment]
The compat bounds are added, so I guess we can release version 0.6.3?

**Comment by mohamed82008** [comment]
Sounds good.

**Comment by devmotion** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/18741.
