### ISSUE TITLE
Unwanted type promotion from Float32 to Float64 while calculating logpdf of TuringDiagMvNormal

### ISSUE THREAD

**Issue by tlauli** [TuringLang/DistributionsAD.jl#156]
While computing logpdf of Multivariate normal distributions, the logpdf is of type Float64, even when the mean, covariance matrix and observation all have eltype Float32.
MVE for TuringDiagMvNormal (TuringScalMvNormal and TuringDenseMvNormal suffer the same problem):
```julia
julia> using Distributions, DistributionsAD
julia> d = TuringDiagMvNormal(zeros(Float32, 2), ones(Float32, 2))
TuringDiagMvNormal{Vector{Float32}, Vector{Float32}}(m=Float32[0.0, 0.0], σ=Float32[1.0, 1.0])
julia> l = logpdf(d, [1f0, 2f0])
-4.337877066409345
julia> typeof(l)
Float64  #expected Float32
```
After a quick glance at the source, the problem seems to be that the constant 2π is Float64, which then promotes the rest of the expression.

**Comment by fedario** [comment]
I'm experiencing the same problem with DistributionsAD v0.6.28
