### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/DistributionsAD.jl#16]
@JuliaRegistrator register()

**Comment by mohamed82008** [comment]
We will need to set upper bounds on all deps. I will do it tomorrow. If you beat me to it @torfjelde, I won't mind though :)

**Comment by torfjelde** [comment]
> If you beat me to it @torfjelde, I won't mind though :)

Haha, have a look at #17 and see what you think:)

**Comment by mohamed82008** [comment]
@JuliaRegistrator register()
