### ISSUE TITLE
MvCategorical needs length method

### ISSUE THREAD

**Issue by bdeonovic** [TuringLang/DistributionsAD.jl#167]
```julia
julia> d = DistributionsAD.MvCategorical(rand(Dirichlet(ones(3)),4))
DistributionsAD.MvDiscreteNonParametric{Int64,Float64,Base.OneTo{Int64},Array{Float64,2}}(
support: Base.OneTo(3)
p: [0.05847351596221934 0.5434796327398905 0.6513029687383283 0.2455728666106314; 0.021949140453810377 0.35427920583290823 0.2725552514012437 0.7255803091385111; 0.9195773435839704 
0.10224116142720104 0.07614177986042824 0.028846824250857384]
)


julia> x = rand(1:3,4)
4-element Array{Int64,1}:
 2
 3
 2
 3

julia> logpdf(d,x)
ERROR: MethodError: no method matching length(::DistributionsAD.MvDiscreteNonParametric{Int64,Float64,Base.OneTo{Int64},Array{Float64,2}})
Closest candidates are:
  length(::Sampleable{Multivariate,S} where S<:ValueSupport) at C:\Users\yim583\.julia\packages\Distributions\cNe2C\src\common.jl:39
  length(::Sampleable) at C:\Users\yim583\.julia\packages\Distributions\cNe2C\src\common.jl:37
  length(::DataStructures.DiBitVector) at C:\Users\yim583\.julia\packages\DataStructures\ixwFs\src\dibit_vector.jl:40
  ...
Stacktrace:
 [1] length(::DistributionsAD.MvDiscreteNonParametric{Int64,Float64,Base.OneTo{Int64},Array{Float64,2}}) at C:\Users\yim583\.julia\packages\Distributions\cNe2C\src\common.jl:39     
 [2] logpdf(::DistributionsAD.MvDiscreteNonParametric{Int64,Float64,Base.OneTo{Int64},Array{Float64,2}}, ::Array{Int64,1}) at C:\Users\yim583\.julia\packages\Distributions\cNe2C\src\multivariates.jl:199
 [3] top-level scope at REPL[64]:1
```

**Comment by devmotion** [comment]
It's very unfortunate that all these half-implemented distributions exist in DistributionsAD for various performance reasons... They are just not checked properly and always out of sync with upstream changes where typically the code was copied from. E.g., https://github.com/TuringLang/DistributionsAD.jl/blob/68d6748a103b4ee569dabce7fd82d937c9ebfbac/src/mvcategorical.jl#L83 is missing the fixes for sampling from `DiscreteNonParametric` in Distributions.

**Comment by bdeonovic** [comment]
i only discovered DistributionsAD today, is there any reason the stuff in here wasn't just added to Distributions?

**Comment by bdeonovic** [comment]
More issues with MvCategorical: https://github.com/TuringLang/DistributionsAD.jl/issues/168

**Comment by devmotion** [comment]
I guess either it was not deemed appropriate for Distributions or people did not want to wait for upstream PRs to be merged.

**Comment by devmotion** [comment]
In general, I am curious why it was added in the first place since most methods just copy the ones for Categorical. To avoid having to slice the matrix of parameters? It seems then one should just make sure that Categorical etc accept views (which I think they do nowadays). Because of differentiation rules? One could add them for Product of Categoricals, I guess.

**Comment by devmotion** [comment]
MvCategorical was removed.
