### ISSUE TITLE
Non-Beta recurrence of "WARNING: could not import DistributionsAD._mv_categorical_logpdf into ReverseDiffX"

### ISSUE THREAD

**Issue by EngrStudent** [TuringLang/DistributionsAD.jl#219]
I have the error in non-beta Julia.

I found this, and though it is closed, and relates to beta, I have the same problem in non-beta.
[https://github.com/TuringLang/DistributionsAD.jl/issues/199](https://github.com/TuringLang/DistributionsAD.jl/issues/199)

When I use this code:
```
using DifferentialEquations
using Plots
using Flux
using DiffEqFlux
```

I get the following warning:
`WARNING: could not import DistributionsAD._mv_categorical_logpdf into ReverseDiffX`

Here is my versioninfo:
```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12th Gen Intel(R) Core(TM) i9-12900KF
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, goldmont)
```

Here is the statuses for my packages:
```
julia> Pkg.status("DifferentialEquations")
      Status `C:\Users\julia> Pkg.status("DifferentialEquations")
      Status `C:\Users\<snip>\.julia\environments\v1.7\Project.toml`
  [0c46a032] DifferentialEquations v7.1.0

julia> Pkg.status("Plots")
      Status `C:\Users\<snip>\.julia\environments\v1.7\Project.toml`
  [91a5bcdd] Plots v1.27.6

julia> Pkg.status("Flux")
      Status `C:\Users\<snip>\.julia\environments\v1.7\Project.toml`
  [587475ba] Flux v0.12.10

julia> Pkg.status("DiffEqFlux")
      Status `C:\Users\<snip>\.julia\environments\v1.7\Project.toml`
  [aae7a2af] DiffEqFlux v1.44.0\.julia\environments\v1.7\Project.toml`
  [0c46a032] DifferentialEquations v7.1.0

```

**Comment by devmotion** [comment]
I assume you use an old version of DistributionsAD and just have to update DistributionsAD. `_mv_categorical_logpdf` was removed from the codebase quite a while ago. You can update to the latest version explicitly with
```julia
julia> ] add DistributionsAD@0.6.38
```
This will also show you if some other package holds back DistributionsAD.

**Comment by EngrStudent** [comment]
I suspect GalacticOptim might have played a part there.  There are a few packages that are downgraded to install the newer version of DistributionsAD.  ModelingToolkit, Symbolics, DiffEqFlux.  

New response from the code, which isn't a warning.
```
┌ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1423
```

You are therefore correct, and the problem is resolved.  Thank you.
