### ISSUE TITLE
`NaN` gradients with Truncated distribution

### ISSUE THREAD

**Issue by marius311** [TuringLang/DistributionsAD.jl#223]
```julia
julia> Zygote.gradient(σ -> logpdf(truncated(Normal(0, σ), 0, Inf), 1), 1)
(NaN,)

julia> ForwardDiff.derivative(σ -> logpdf(truncated(Normal(0, σ), 0, Inf), 1), 1)
NaN
```

The issue is in the definition of `truncated`, and its the `Inf` that's the problem. Changing it to a large but finite number fixes things. 

I think a custom rrule for `truncated` could be one way to fix Zygote but to also get ForwardDiff maybe the best way is to tweak that function to be a little more AD friendly.

**Comment by devmotion** [comment]
IIRC ForwardDiff works correctly if you use the NaN-safe mode (there were some issues about this in Distributions and discussions on Slack a while ago).

In general, the plan is ultimately to not use `Inf` but `nothing` in Distributions, as we do already for e.g. `censored`. We also try to reduce (and possibly at some point get rid of) DistributionsAD and upstream stuff to eg Distributions and the different AD backends, so I'd like to avoid adding new things to DistributionsAD.

**Comment by devmotion** [comment]
I just checked and it seems the `censored`-like interface which we added to `truncated` (but still sets the upper limit to `Inf` internally to avoid breaking changes) fixes these examples:
```julia
julia> using Distributions, ForwardDiff, Zygote

julia> Zygote.gradient(σ -> logpdf(truncated(Normal(0, σ); lower=0), 1), 1)
(0.0,)

julia> Zygote.gradient(σ -> logpdf(truncated(Normal(0, σ); lower=0), 1), 10)
(-0.099,)

julia> ForwardDiff.derivative(σ -> logpdf(truncated(Normal(0, σ); lower=0), 1), 1)
0.0

julia> ForwardDiff.derivative(σ -> logpdf(truncated(Normal(0, σ); lower=0), 1), 10)
-0.099
```

**Comment by marius311** [comment]
Ah ok, awesome, I didn't know `truncated` has that. That pretty much solves it for me, up to you if you want to keep this open at all.

**Comment by devmotion** [comment]
OK, I'll close this issue then :slightly_smiling_face:
