### ISSUE TITLE
Extension of Distributions for AD rules

### ISSUE THREAD

**Issue by prbzrg** [TuringLang/DistributionsAD.jl#255]
There is an extension of [`Distributions` for AD rules](https://github.com/JuliaStats/Distributions.jl/tree/master/ext/DistributionsChainRulesCoreExt) . Which one should be used `DistributionsAD` or extension of `Distributions`?

**Comment by devmotion** [comment]
As a user? The ultimate goal is to make DistributionsAD (and its type piracies) obsolete by moving its content to (extensions of) Distributions and other upstream packages such as ReverseDiff, Zygote etc. But until this transition is completed, some AD-related things with Distributions won't work correctly if you don't use DistributionsAD. I suggest though checking first if you really need DistributionsAD - it contains a lot of type piracy, so if you don't need it and everything works fine without it, better don't use it :slightly_smiling_face: 

The extension of Distributions will be loaded automatically if you (or a dependency) loads ChainRulesCore, you can't control this apart from (not) loading ChainRulesCore.

**Comment by prbzrg** [comment]
Thank you for your response
