### ISSUE TITLE
Support for Zygote

### ISSUE THREAD

**Issue by paschermayr** [TuringLang/DistributionsAD.jl#9]
First of all, congratulations to this module - it just made my (and many others) life so much easier! 

Apologies if this inquiry does not 100% belong to the issues section, but I wanted to ask if there are also plans to add Zygote to the supported AD modules? Taking derivatives from dict-like objects sounds amazing if you do sampling based inference. 

Best regards!

**Comment by mohamed82008** [comment]
Thanks for your kind words. Supporting Zygote should be possible in theory. It may already be supported for some of the distributions but we need proper tests. I will work on it soon-ish.

**Comment by paschermayr** [comment]
Thank you very much! I would love to just throw all parameter in a container and then define a likelihood function for it. This is already possible for Zygote but I just cant get it to work for certain distributions (Hey, MvNormal...). Is there a rough time estimate when Zygote might be supported by DistributionsAD?

**Comment by mohamed82008** [comment]
Sorry for not getting back to you earlier. There is no clear timeline unfortunately. It depends on:
1. When I get time to do it (perhaps others can chime in), and
2. If Zygote is actually ready for this, Zygote bugs are usually not fixable by most Julia programmers, only a few who are familiar with the internals of the Julia compiler.

I will try to make time to look into this in the next few weeks.

**Comment by mohamed82008** [comment]
We will have Zygote support after https://github.com/TuringLang/DistributionsAD.jl/pull/25 is merged and a release is made.

**Comment by mohamed82008** [comment]
Closed via #25.
